#!/bin/bash
# ar workalike for Open Watcom, creation only

CMD="$1"
FILE="$2"
WOPT="-fag"
shift; shift

# Figure out the command length
CMDL=${#CMD}
for (( i = 0; i < CMDL; i++ ))
do
    CMDC=${CMD:$i:1}
    case "$CMDC" in
        -) ;;
        r) ;;
        u) ;;
        c)
            WOPT="$WOPT -n"
            ;;

        *)
            echo 'Unrecognized option '"$CMDC"
            exit 1
            ;;
    esac
done

exec wlib $WOPT "$FILE" "$@"
